[[authors]]
email = "cth451@gmail.com"
name.default = "cth451"

[[wallpapers]]
title.default = "Luray in Twilight"
title.zh-CN = "卢雷日暮"
license = "CC-BY-NC-4.0"
id = "Luray_in_Twilight"
path = "Luray_in_Twilight.jpg"

[[wallpapers]]
title.default = "Northern Mocking Bird"
title.zh-CN = "北方嘲鸫"
license = "CC-BY-NC-4.0"
id = "Northern_Mocking_Bird"
path = "Northern_Mocking_Bird.jpg"

[[wallpapers]]
title.default = "Pounding Waves"
title.zh-CN = "浪涛拍岸"
license = "CC-BY-NC-4.0"
id = "Pounding_Waves"
path = "Pounding_Waves.jpg"

[[wallpapers]]
title.default = "Sunset at Glacier Point"
title.zh-CN = "冰山日暮"
license = "CC-BY-4.0"
id = "Sunset_at_Glacier_Point"
path = "Sunset_at_Glacier_Point.jpg"

[[wallpapers]]
title.default = "Dome"
title.zh-CN = "天穹"
license = "CC-BY-4.0"
id = "Dome"
path = "Dome.jpg"
